git clone git@github.com:meerkat-code/meerkat_abacus.git
git clone git@github.com:meerkat-code/meerkat_frontend.git
git clone git@github.com:meerkat-code/meerkat_api.git
git clone git@github.com:meerkat-code/meerkat_demo.git
git clone git@github.com:meerkat-code/meerkat_djibouti.git
git clone git@github.com:meerkat-code/meerkat_docs.git
git clone git@github.com:meerkat-code/meerkat_hermes.git
git clone git@github.com:meerkat-code/meerkat_infrastructure.git
git clone git@github.com:meerkat-code/meerkat_jordan.git
git clone git@github.com:meerkat-code/meerkat_mad.git
git clone git@github.com:meerkat-code/meerkat_rms.git
